name: build-and-release

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
  release:
    types: [ "created" ]

jobs:
  build:
    runs-on: macos-14
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install XcodeGen
        run: brew install xcodegen

      - name: Generate Xcode project
        run: xcodegen generate

      - name: Build .saver (Release)
        run: |
          xcodebuild -project SpaceInvadersSaver.xcodeproj -scheme SpaceInvadersSaver -configuration Release -derivedDataPath build CODE_SIGNING_ALLOWED=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY="" build

      - name: Pack artifact
        run: |
          cd build/Build/Products/Release
          zip -r SpaceInvadersSaver.zip SpaceInvadersSaver.saver
          mv SpaceInvadersSaver.zip $GITHUB_WORKSPACE/

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: SpaceInvadersSaver
          path: SpaceInvadersSaver.zip

  release:
    needs: build
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: macos-14
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: SpaceInvadersSaver
          path: .

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: SpaceInvadersSaver.zip
